# Generated by Django 2.2.2 on 2019-06-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190609_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='selected_option',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
