# Generated by Django 2.2.2 on 2019-06-10 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_auto_20190610_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='student',
        ),
        migrations.AddField(
            model_name='response',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
