# Generated by Django 2.2.2 on 2019-06-10 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190610_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='student',
        ),
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
    ]
