# Generated by Django 2.2.2 on 2019-06-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('quiz', '0007_auto_20190610_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='student',
            field=models.ManyToManyField(to='Users.Profile'),
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ManyToManyField(to='Users.Profile'),
        ),
    ]
