# Generated by Django 2.2.2 on 2019-06-11 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20190611_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Test'),
        ),
    ]
