# Generated by Django 2.2.2 on 2019-06-11 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20190611_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Options'),
        ),
    ]
